# docker-compose.yml
# Локальное окружение для разработки
#
# Запуск:    docker compose up -d
# Остановка: docker compose down
# Логи:      docker compose logs -f

services:
  # ---------------------------------------------------------------------------- #
  # PostgreSQL
  # ---------------------------------------------------------------------------- #
  catalog-postgres:
    ports:
      - '5429:5432'
    container_name: 'catalog-postgres'
    # https://hub.docker.com/_/postgres
    image: 'postgres:15.1-alpine'
    restart: 'unless-stopped'
    environment:
      POSTGRES_USER: 'admin'
      POSTGRES_PASSWORD: 'admin'
      POSTGRES_DB: 'catalog_db'
    volumes:
      - 'catalog_postgres_data:/var/lib/postgresql/data'
    networks:
      - backend_net
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U admin -d catalog_db"]
      interval: 5s
      timeout: 5s
      retries: 5

  order-postgres:
    container_name: "order-postgres"
    image: "postgres:16-alpine"
    restart: "unless-stopped"
    ports:
      - "7432:5432"
    environment:
      POSTGRES_USER: "order_user"
      POSTGRES_PASSWORD: "secret"
      POSTGRES_DB: "order_db"
    volumes:
      - "order_data:/var/lib/postgresql/data"
    networks:
      - backend_net
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U order_user -d order_db"]
      interval: 5s
      timeout: 5s
      retries: 5
  
  order-service:
    build:
      context: .
      dockerfile: Dockerfile  
    container_name: order-service
    restart: always
    ports:
      - "9020:9020"  
    depends_on:
      order-postgres:
        condition: service_healthy
    environment: 
      POSTGRES_DB: "order_db"  
      POSTGRES_USER: "order_user"
      POSTGRES_PASSWORD: "secret"
      POSTGRES_HOST: "localhost"
      POSTGRES_PORT: "7432"
    networks:
      - backend_net

  catalog-service:
    build:
      context: ../catalog-service
      dockerfile: Dockerfile  
    container_name: catalog-service
    restart: always
    ports:
      - "8080:8080"  
      - "8081:8081"
      - "50051:50051"    
    depends_on:
      catalog-postgres:
        condition: service_healthy
    environment: 
      POSTGRES_DB: "catalog_db"  
      POSTGRES_USER: "admin"
      POSTGRES_PASSWORD: "admin"
      POSTGRES_HOST: "catalog-postgres"
      POSTGRES_PORT: "7432"
    networks:
      - backend_net


# ---------------------------------------------------------------------------- #
# Volumes
# ---------------------------------------------------------------------------- #
volumes:
  catalog_postgres_data: {}
  order_data: {}

# ---------------------------------------------------------------------------- #
# Networks
# ---------------------------------------------------------------------------- #
networks:
  backend_net:
    driver: bridge
